"Ok so i started by making a tutorial in console, went on to creating a"
"console app which echoed key input data."
"I created a few class variables defining the game enviroment"
"including characters units groups timers triggers doodaads and items"
"i noticed i can create strings, export unit data."
"with xml files and parser them to C#."
"i seperated the game dev actions into areas, objects, units,"
"conditions triggers and events."
"we have doodads and items to think about too."
"was hoping to work on initilizing game time."
"and object selection."
"like gui menu options."
"remind yourself of its physics system and script accordingly."
"Space time gravity and matter e=mc**2"
